### ISSUE TITLE
‼️

### ISSUE THREAD

**Issue by ZyvoksCode** [aeziotech/bunny-logger#2]
le message de jointure ne sera pas envoyé et les emojis sont cassés, il dit que toString n'est pas une fonction!

**Comment by aeziotech** [comment]
Bonjour @ZyvoksCode . Tu dois ajouter toi même les émoji. Je créer de suite un fichier avec les émojis nécessaire que tu devras ajouter à ton serveur ! Cependant, tu n'est pas obligé de prendre exactement les même, il faudra juste modifier leur noms dans le config.js ! Je le met dans quelques secondes !

**Comment by aeziotech** [comment]
@ZyvoksCode Je viens d'ajouter le dossier avec les émojis. Ils se trouve dans le chemin suivant :
 - assets/emojis/
